services:
  - type: web
    name: whatsapp-bot-smapac
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: API_CONTRATOS_URL
        value: https://restserver-smapac.herokuapp.com/api/
      - key: URL_CLIENT
        value: https://smapac.gob.mx/pagaturecibo/